from enum import IntEnum

class States(IntEnum):
    START = 0
    MAIN_MENU = 1
    HELP_MENU = 2
    TYPING = 3
    FAQ_LEGAL = 4
    MEDICAL_MENU = 5
    VOLUNTEER_START_STATE = 6
    VOLUNTEER_NAME = 7
    VOLUNTEER_REGION = 8
    VOLUNTEER_HELP_TYPE = 9
    VOLUNTEER_CONTACT = 10
    ANONYMOUS_MESSAGE = 11
    MEDICAL_GENDER_THERAPY_MENU = 12
    MEDICAL_FTM_HRT = 13
    MEDICAL_MTF_HRT = 14
    MEDICAL_SURGERY_PLANNING = 15
    DONE = 16
